In [9]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline

[Learn the Basics](intro.html) \|\|
[Quickstart](quickstart_tutorial.html) \|\| **Tensors** \|\| [Datasets &
DataLoaders](data_tutorial.html) \|\|
[Transforms](transforms_tutorial.html) \|\| [Build
Model](buildmodel_tutorial.html) \|\|
[Autograd](autogradqs_tutorial.html) \|\|
[Optimization](optimization_tutorial.html) \|\| [Save & Load
Model](saveloadrun_tutorial.html)

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to [NumPy's](https://numpy.org/) ndarrays, except
that tensors can run on GPUs or other hardware accelerators. In fact,
tensors and NumPy arrays can often share the same underlying memory,
eliminating the need to copy data (see
`bridge-to-np-label`{.interpreted-text role="ref"}). Tensors are also
optimized for automatic differentiation (we\'ll see more about that
later in the [Autograd](autogradqs_tutorial.html) section). If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along!

---


텐서(Tensors)
=======

텐서는 배열 및 행렬과 매우 유사한 특수한 데이터 구조입니다. PyTorch에서는 텐서를 사용하여 모델의 입력 및 출력뿐만 아니라 모델의 매개변수도 인코딩합니다.

텐서는 [NumPy의](https://numpy.org/) ndarrays와 유사하지만, 텐서는 GPU 또는 기타 하드웨어 가속기에서 실행될 수 있습니다. 실제로 텐서와 NumPy 배열은 종종 동일한 기본 메모리를 공유하여 데이터 복사의 필요성을 제거합니다 (자세한 내용은 `bridge-to-np-label`{.interpreted-text role="ref"}를 참조하십시오). 텐서는 또한 자동 미분을 위해 최적화되어 있습니다 (이 부분에 대해서는 [자동 미분(Autograd)](autogradqs_tutorial.html) 섹션에서 더 자세히 다룰 것입니다). ndarrays에 익숙하다면 Tensor API도 쉽게 익힐 수 있습니다. 그렇지 않더라도, 함께 따라오세요!

---

In [10]:
import torch
import numpy as np

Initializing a Tensor
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.

---

텐서 초기화
=====================

텐서는 다양한 방법으로 초기화할 수 있습니다. 다음 예제를 살펴보세요:

**데이터에서 직접 생성하기**

텐서는 데이터를 사용하여 직접 생성할 수 있습니다. 데이터 유형은 자동으로 추론됩니다.

---

In [11]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [12]:
data

[[1, 2], [3, 4]]

In [13]:
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).

---

**NumPy 배열에서**

텐서는 NumPy 배열에서 생성할 수 있습니다 (반대의 경우도 가능하며, 자세한 내용은 `bridge-to-np-label`{.interpreted-text role="ref"}를 참조하세요).

---

In [14]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_np

tensor([[1, 2],
        [3, 4]])

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.

---

**다른 텐서에서:**

새 텐서는 argument 텐서의 속성(형상, 데이터 유형)을 유지합니다. 단, 명시적으로 재정의하지 않는 경우에 한합니다.

---

In [15]:
x_ones = torch.ones_like(x_data)  # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # x_data의 데이터 유형을 재정의합니다.
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6047, 0.7297],
        [0.9613, 0.7713]]) 



**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.

---

**무작위 또는 상수 값으로:**

`shape`는 텐서의 차원을 나타내는 튜플입니다. 아래 함수에서 `shape`는 출력 텐서의 차원을 결정합니다.

---

In [16]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3717, 0.4529, 0.9525],
        [0.5768, 0.2006, 0.6163]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Attributes of a Tensor
======================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.

---

텐서의 속성
======================

텐서의 속성은 텐서의 형상, 데이터 유형 및 저장되는 장치를 설명합니다.

---


In [17]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Operations on Tensors
=====================

Over 100 tensor operations, including arithmetic, linear algebra, matrix
manipulation (transposing, indexing, slicing), sampling and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the GPU (at typically higher
speeds than on a CPU). If you're using Colab, allocate a GPU by going to
Runtime \> Change runtime type \> GPU.

By default, tensors are created on the CPU. We need to explicitly move
tensors to the GPU using `.to` method (after checking for GPU
availability). Keep in mind that copying large tensors across devices
can be expensive in terms of time and memory!

---

텐서에 대한 연산
=====================

산술, 선형 대수, 행렬 조작(전치, 인덱싱, 슬라이싱), 샘플링 등 100개 이상의 텐서 연산이 [여기](https://pytorch.org/docs/stable/torch.html)에서 포괄적으로 설명됩니다.

이러한 연산은 GPU에서 실행될 수 있으며(일반적으로 CPU보다 더 높은 속도로 수행됨), Colab을 사용하는 경우 Runtime > Change runtime type > GPU로 이동하여 GPU를 할당할 수 있습니다.

기본적으로 텐서는 CPU에서 생성됩니다. 우리는 GPU의 가용성을 확인한 후 `.to` 메서드를 사용하여 텐서를 명시적으로 GPU로 이동해야 합니다. 장치 간에 큰 텐서를 복사하는 것은 시간과 메모리 측면에서 비용이 많이 들 수 있다는 점을 유의하세요!

---

In [18]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.

---

리스트에서 몇 가지 연산을 시도해 보세요. NumPy API에 익숙하다면 Tensor API를 사용하는 것이 매우 간편할 것입니다.

---

**Standard numpy-like indexing and slicing:**


In [19]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [20]:
data = [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4], 
        [1, 2, 3, 4]]

data_tensor = torch.tensor(data)
print(f"First row: {data_tensor[0]}")
print(f"First column: {data_tensor[:, 0]}")
print(f"Last column: {data_tensor[..., -1]}")
data_tensor[:,1] = 0
print(data_tensor)

First row: tensor([1, 2, 3, 4])
First column: tensor([1, 1, 1, 1])
Last column: tensor([4, 4, 4, 4])
tensor([[1, 0, 3, 4],
        [1, 0, 3, 4],
        [1, 0, 3, 4],
        [1, 0, 3, 4]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining operator that is subtly different from
`torch.cat`.

---

**텐서 결합** `torch.cat`을 사용하여 주어진 차원에 따라 텐서의 시퀀스를 연결할 수 있습니다. `torch.cat`과 미세하게 다른 또 다른 텐서 결합 연산자인 [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)도 참고하세요.

---

In [21]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Arithmetic operations**


In [31]:
# 이것은 두 텐서 간의 행렬 곱셈을 계산합니다. y1, y2, y3는 같은 값을 가집니다.
# ``tensor.T``는 텐서의 전치를 반환합니다.
y1 = tensor @ tensor.T
print("y1: \n ", y1)
y2 = tensor.matmul(tensor.T)
print("y2: \n ", y2)


y3 = torch.rand_like(y1)
print("y3: \n ", y3)
print(torch.matmul(tensor, tensor.T, out=y3))


# 이것은 원소별 곱셈을 계산합니다. z1, z2, z3는 같은 값을 가집니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)

print("z1: \n", z1, "\nz2: \n", z2, "\nz3: \n", z3)

print(torch.mul(tensor, tensor, out=z3))


y1: 
  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: 
  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: 
  tensor([[0.6846, 0.0590, 0.6795, 0.1334],
        [0.7311, 0.7193, 0.7131, 0.4742],
        [0.1620, 0.4593, 0.7031, 0.9309],
        [0.0532, 0.7897, 0.8161, 0.5051]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
z2: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
z3: 
 tensor([[0.5807, 0.7786, 0.4960, 0.1793],
        [0.9465, 0.9595, 0.0274, 0.5889],
        [0.7406, 0.9263, 0.7011, 0.1073],
        [0.5287, 0.0305, 0.2977, 0.0725]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1

**Single-element tensors** If you have a one-element tensor, for example
by aggregating all values of a tensor into one value, you can convert it
to a Python numerical value using `item()`:

---

**단일 요소 텐서** 만약 하나의 요소만 있는 텐서가 있다면, 예를 들어 텐서의 모든 값을 하나의 값으로 집계한 경우, `item()`을 사용하여 이를 Python 숫자 값으로 변환할 수 있습니다:

---

In [32]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**In-place operations** Operations that store the result into the
operand are called in-place. They are denoted by a `_` suffix. For
example: `x.copy_(y)`, `x.t_()`, will change `x`.

---

**제자리 연산** 결과를 피연산자에 저장하는 연산을 제자리 연산이라고 합니다. 이들은 `_` 접미사로 표시됩니다. 예를 들어: `x.copy_(y)`, `x.t_()`는 `x`를 변경합니다.

---


In [33]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [34]:
tensor.add(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [35]:
tensor.add_(5)
print(tensor)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>
<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">
<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>
</div>

---

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>참고:</strong></div>
<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">
<p>제자리 연산은 메모리를 절약할 수 있지만, 즉각적인 이력 손실로 인해 미분을 계산할 때 문제가 될 수 있습니다. 따라서 이러한 사용은 권장되지 않습니다.</p>
</div>

---

------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.

---

NumPy와의 연결 {#bridge-to-np-label}
=================

CPU에서의 텐서와 NumPy 배열은 기본 메모리 위치를 공유할 수 있으며, 하나를 변경하면 다른 것도 변경됩니다.

---

Tensor to NumPy array
=====================


In [36]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

---

텐서의 변경 사항은 NumPy 배열에 반영됩니다.

---

In [37]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [38]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

---

NumPy 배열의 변경 사항은 텐서에 반영됩니다.

---

In [39]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
